### ISSUE TITLE
Firebase Schema

### ISSUE THREAD

**Issue by jennykim1016** [dragonrollers/thoughtbubble-app#1]
Draft 1.

<img width="434" alt="screen shot 2017-11-17 at 3 02 07 pm" src="https://user-images.githubusercontent.com/18297066/32972678-58bf885c-cba8-11e7-89fd-dcacafe92a05.png">

Draft 2.

<img width="652" alt="screen shot 2017-11-17 at 3 02 10 pm" src="https://user-images.githubusercontent.com/18297066/32972680-5d2067fe-cba8-11e7-8f9f-6ea401b15e70.png">

Final schema

<img width="694" alt="screen shot 2017-11-17 at 3 29 34 pm" src="https://user-images.githubusercontent.com/18297066/32973415-2a355936-cbac-11e7-94f7-5e2a67523420.png">

**Comment by potsui** [comment]
I think we all know this by heart now / can just look at Firebase console, so closing this!
