### ISSUE TITLE
Android Frontend Tasks

### ISSUE THREAD

**Issue by jennykim1016** [dragonrollers/thoughtbubble-app#11]
## TO DO
- [ ] Make fragment layout for saving to a board (`Discover` tab)
- [ ] Make boards smaller and let second board on right show more so users know they can swipe (`User` tab)
- [ ] Split `Discover` tab into two views: 1) your asked questions 2) other people's questions
- [ ] Search for boards in list mode (`User` tab)

## Done
- [x] profile page -> implement both public and private
- [x] somehow hack the toolbar
- [x] Toggle the text while revising the question : https://www.google.com/search?q=android+toggle+button&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjDld2q5-TXAhXLu7wKHdZ7AFwQ_AUICigB&biw=1278&bih=627#imgrc=1SyFkXi7U5B6lM: on-off controls the view of revised questions

**Comment by jennykim1016** [comment]
Closing #2

**Comment by jennykim1016** [comment]
- [ ] main page where we prompt the users to sign in if they are not signed in

**Comment by potsui** [comment]
Consolidating TODOs with #16
