### ISSUE TITLE
Loading User's Profile Picture in the Database

### ISSUE THREAD

**Issue by jennykim1016** [dragonrollers/thoughtbubble-app#29]
Hi @potsui and @bnortz ,

Right now discover page doesn't load the user's photo -- if we can fix that, the discover feed would look much better :D

**Comment by potsui** [comment]
@jennykim1016 @bnortz I can take this, since I've been working with Firebase storage

**Comment by potsui** [comment]
Also more generally I'll be responsible for loading profile pictures in the entire app where they're needed

**Comment by potsui** [comment]
Broken down to more specific pages
