### ISSUE TITLE
Enable Search for Users

### ISSUE THREAD

**Issue by jennykim1016** [dragonrollers/thoughtbubble-app#32]
I think even for the prototype, having this functionality is important (otherwise the user would not be able to find anyone to ask questions to T_T ).

I will try to hack the hamburger and implement a flow to find a new user. Could any one of you @bnortz @potsui take care of the backend? I will post here once I am done with it.

**Comment by potsui** [comment]
@jennykim1016 to clarify, does this refer to finding new friends or just searching for existing friend?

**Comment by jennykim1016** [comment]
Finding new friends! uh you are right though we should be able to search for existing friends

**Comment by potsui** [comment]
Oh oops I made a duplicate then #37

**Comment by bnortz** [comment]
Doing a work-around for prototype
