### ISSUE TITLE
Package into .apk and upload to website

### ISSUE THREAD

**Issue by potsui** [dragonrollers/thoughtbubble-app#33]
Please do so leaving me enough time to upload the website with our week 9-10 materials, since I will be working on both the app and the website.

**Comment by potsui** [comment]
From Piazza:
https://stackoverflow.com/questions/16622843/how-do-i-export-a-project-in-the-android-studio
https://www.youtube.com/watch?v=Qatec8l3XOI

**Comment by jennykim1016** [comment]
Closing the issue!
