### ISSUE TITLE
Profile Page Interest Layout

### ISSUE THREAD

**Issue by jennykim1016** [dragonrollers/thoughtbubble-app#34]
@gracehong Could you take care of the error where interests go out-of-layout? Thanks!

**Comment by potsui** [comment]
The + button also disappears

**Comment by jennykim1016** [comment]
Please pull master before changing -- I fixed few details in the profile layout page

**Comment by jennykim1016** [comment]
@gracehong if you could improve the general design of the profile page, that would be really great too! Right now it looks a little weird :'(

**Comment by gracehong** [comment]
Yep I got u
