### ISSUE TITLE
Change AskSelect and Discover to dynamically load friends' names based on given user ids

### ISSUE THREAD

**Issue by potsui** [dragonrollers/thoughtbubble-app#35]
Currently their names are also stored and won't be updated when that friend edits their name.

**Comment by bnortz** [comment]
I can work on this today! I have a good way of reorganizing the database to do this - found an article of some best practices that explained some good things (that's super vague but trust me XD)

**Comment by jennykim1016** [comment]
@bnortz can we close this? 👯

**Comment by bnortz** [comment]
Yup, finally made the change to profile to make it all consistent!
