### ISSUE TITLE
Validate user inputs

### ISSUE THREAD

**Issue by potsui** [dragonrollers/thoughtbubble-app#36]
Prevent user from submitting if input is null, etc. Other sorts of error checking and validation where applicable

**Comment by jennykim1016** [comment]
@potsui Do we just have to check whether the textfield is empty? Or do you need to do more firebase-related checks?

**Comment by gracehong** [comment]
I just merged support for making sure the user doesn't enter an empty name, empty interest field, empty answers (empty revisions are ok) or asks

**Comment by potsui** [comment]
Addressed with #48
