### ISSUE TITLE
Pass in IDs where possible

### ISSUE THREAD

**Issue by potsui** [dragonrollers/thoughtbubble-app#40]
For questions, users, etc. please pass in their IDs where possible (instead of just name) which will prevent us from going back to fix them later. That's because *important note: all database interactions are by ID* and if we just had the name you would have to search linearly through the results.

**Comment by bnortz** [comment]
@potsui where is this an issue right now? For the parts I've worked on, the IDs are passed through intents

**Comment by potsui** [comment]
@bnortz this was more of a general request since I've been changing them as I went along where needed, but thought there might be more out there

**Comment by bnortz** [comment]
👍  Turns out there was at least one more, in the boards list!

**Comment by potsui** [comment]
Hopefully with the board branch and Bonnie's changes this is fully addressed. Closing for now.
