### ISSUE TITLE
Discover all questions does not include the questions you've answered?

### ISSUE THREAD

**Issue by gracehong** [dragonrollers/thoughtbubble-app#52]
If I answer one of my unanswered questions and then go to discover, I don't see it appear in the all questions list 😱

**Comment by bnortz** [comment]
This is intentional - the idea being that if you're looking to discover new content, you don't want to see questions that you've answered. @gracehong , @potsui , @jennykim1016 should we change that? It's really simple to do 🙂

**Comment by potsui** [comment]
I think that makes sense! You wouldn't need to discover your own, plus it's already stored under a different tab. Closing for now but anybody who objects, feel free to reopen.
