### ISSUE TITLE
[MAJOR] (From Grace) Weird revision dialogue box when answering a question

### ISSUE THREAD

**Issue by bnortz** [dragonrollers/thoughtbubble-app#55]
When you attempt to answer a question--for some reason, the "do you want to make revisions" dialog box pops up in response to clicking on the question, and only when you respond to it does it let you view the detailed question.

**Comment by bnortz** [comment]
I think this was a bit of a miscommunication with Jenny as she was working on this - there shouldn't be this dialog box that pops up, but the toggle for "Your Revised Question" just needs more information explaining what it means on the AnswerQuestion page

**Comment by potsui** [comment]
Fixed with PR #64
