### ISSUE TITLE
Crash when trying to view question from Answered

### ISSUE THREAD

**Issue by bnortz** [dragonrollers/thoughtbubble-app#73]

**Comment by jennykim1016** [comment]
I think this is a backend issue. I saw the same problem with the board before which @potsui fixed today.

Error Message:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{edu.stanford.cs147.thoughtbubble_app/edu.stanford.cs147.thoughtbubble_app.SeeDetailedQuestion}: java.lang.NullPointerException: Can't pass null for argument 'pathString' in child()`
